from pathlib import Path
import sys

root = Path(sys.argv[1])


def must_replace(text, old, new, label):
    if old not in text:
        raise SystemExit(f"{label} not found")
    return text.replace(old, new, 1)

# -----------------------------------------------------------------------------
# AppState: keep HTML generated by the compact WYSIWYG editor alongside the
# plain-text body. Plain text remains the fallback for Outlook and accessibility.
# -----------------------------------------------------------------------------
p = root / "app" / "AppState.swift"
s = p.read_text()
s = must_replace(
    s,
    '    @Published var reply: String = ""\n',
    '    @Published var reply: String = ""\n    @Published var replyHTML: String = ""\n',
    "AppState replyHTML",
)
p.write_text(s)

# -----------------------------------------------------------------------------
# New compact rich-text editor. It is a native NSTextView, so it is genuinely
# WYSIWYG rather than a markdown preview. The tiny toolbar offers bold, italic,
# bullets, numbering and clear formatting. The coordinator continuously exports
# the current body as both plain text and HTML.
# -----------------------------------------------------------------------------
rich_editor = r'''import SwiftUI
import AppKit

final class RichTextEditorController: ObservableObject {
    weak var textView: NSTextView?

    func toggleBold() {
        toggleFontTrait(.boldFontMask)
    }

    func toggleItalic() {
        toggleFontTrait(.italicFontMask)
    }

    func toggleBullets() {
        toggleList(style: .bullets)
    }

    func toggleNumbering() {
        toggleList(style: .numbered)
    }

    func clearFormatting() {
        guard let textView, let storage = textView.textStorage else { return }
        let range = effectiveSelection(in: textView)
        guard range.length > 0 else {
            textView.typingAttributes = [.font: NSFont.systemFont(ofSize: 14)]
            return
        }
        storage.beginEditing()
        storage.removeAttribute(.font, range: range)
        storage.removeAttribute(.foregroundColor, range: range)
        storage.removeAttribute(.backgroundColor, range: range)
        storage.removeAttribute(.underlineStyle, range: range)
        storage.removeAttribute(.strikethroughStyle, range: range)
        storage.addAttribute(.font, value: NSFont.systemFont(ofSize: 14), range: range)
        storage.endEditing()
        textView.didChangeText()
    }

    private func toggleFontTrait(_ trait: NSFontTraitMask) {
        guard let textView, let storage = textView.textStorage else { return }
        let selected = textView.selectedRange()
        let manager = NSFontManager.shared

        if selected.length == 0 {
            let current = (textView.typingAttributes[.font] as? NSFont) ?? NSFont.systemFont(ofSize: 14)
            let hasTrait = manager.traits(of: current).contains(trait)
            let converted = hasTrait
                ? manager.convert(current, toNotHaveTrait: trait)
                : manager.convert(current, toHaveTrait: trait)
            textView.typingAttributes[.font] = converted
            return
        }

        var firstTraitState: Bool?
        storage.enumerateAttribute(.font, in: selected) { value, _, stop in
            let font = (value as? NSFont) ?? NSFont.systemFont(ofSize: 14)
            firstTraitState = manager.traits(of: font).contains(trait)
            stop.pointee = true
        }
        let removeTrait = firstTraitState ?? false

        storage.beginEditing()
        storage.enumerateAttribute(.font, in: selected) { value, range, _ in
            let font = (value as? NSFont) ?? NSFont.systemFont(ofSize: 14)
            let converted = removeTrait
                ? manager.convert(font, toNotHaveTrait: trait)
                : manager.convert(font, toHaveTrait: trait)
            storage.addAttribute(.font, value: converted, range: range)
        }
        storage.endEditing()
        textView.didChangeText()
    }

    private enum ListStyle { case bullets, numbered }

    private func toggleList(style: ListStyle) {
        guard let textView, let storage = textView.textStorage else { return }
        let ns = textView.string as NSString
        let selected = effectiveSelection(in: textView)
        let paragraphRange = ns.paragraphRange(for: selected)
        guard paragraphRange.length > 0 else { return }

        var starts: [Int] = []
        var cursor = paragraphRange.location
        let end = NSMaxRange(paragraphRange)
        while cursor < end {
            starts.append(cursor)
            let line = ns.lineRange(for: NSRange(location: cursor, length: 0))
            let next = NSMaxRange(line)
            if next <= cursor { break }
            cursor = next
        }

        func existingPrefixLength(at start: Int, in string: NSString) -> Int {
            let remaining = string.substring(from: start)
            if remaining.hasPrefix("• ") { return 2 }
            if remaining.hasPrefix("- ") { return 2 }
            let prefix = String(remaining.prefix(8))
            if let match = prefix.range(of: #"^\d+\.\s"#, options: .regularExpression) {
                return prefix.distance(from: prefix.startIndex, to: match.upperBound)
            }
            return 0
        }

        let shouldRemove: Bool = {
            switch style {
            case .bullets:
                return starts.allSatisfy { (textView.string as NSString).substring(from: $0).hasPrefix("• ") }
            case .numbered:
                return starts.allSatisfy {
                    let prefix = String((textView.string as NSString).substring(from: $0).prefix(8))
                    return prefix.range(of: #"^\d+\.\s"#, options: .regularExpression) != nil
                }
            }
        }()

        storage.beginEditing()
        for (reverseIndex, start) in starts.enumerated().reversed() {
            let currentString = storage.string as NSString
            let oldPrefixLength = existingPrefixLength(at: start, in: currentString)
            if oldPrefixLength > 0 {
                storage.deleteCharacters(in: NSRange(location: start, length: oldPrefixLength))
            }
            if !shouldRemove {
                let prefix: String
                switch style {
                case .bullets:
                    prefix = "• "
                case .numbered:
                    prefix = "\(reverseIndex + 1). "
                }
                let attrs: [NSAttributedString.Key: Any]
                if start < storage.length {
                    attrs = storage.attributes(at: start, effectiveRange: nil)
                } else {
                    attrs = [.font: NSFont.systemFont(ofSize: 14)]
                }
                storage.insert(NSAttributedString(string: prefix, attributes: attrs), at: start)
            }
        }
        storage.endEditing()
        textView.didChangeText()
    }

    private func effectiveSelection(in textView: NSTextView) -> NSRange {
        let selection = textView.selectedRange()
        if selection.length > 0 { return selection }
        let length = (textView.string as NSString).length
        if length == 0 { return NSRange(location: 0, length: 0) }
        let safeLocation = min(selection.location, max(0, length - 1))
        return (textView.string as NSString).paragraphRange(for: NSRange(location: safeLocation, length: 0))
    }
}

struct RichTextMailEditor: View {
    @Binding var plainText: String
    @Binding var html: String
    @StateObject private var controller = RichTextEditorController()

    var body: some View {
        VStack(spacing: 0) {
            HStack(spacing: 5) {
                formatButton(title: "B", help: "Fett", action: controller.toggleBold)
                    .font(.system(size: 12, weight: .bold))
                formatButton(title: "I", help: "Kursiv", action: controller.toggleItalic)
                    .font(.system(size: 12).italic())

                Divider().frame(height: 18).padding(.horizontal, 2)

                Button(action: controller.toggleBullets) {
                    Image(systemName: "list.bullet")
                        .frame(width: 22, height: 20)
                }
                .buttonStyle(.borderless)
                .help("Aufzählung")

                Button(action: controller.toggleNumbering) {
                    Image(systemName: "list.number")
                        .frame(width: 22, height: 20)
                }
                .buttonStyle(.borderless)
                .help("Nummerierte Liste")

                Divider().frame(height: 18).padding(.horizontal, 2)

                Button(action: controller.clearFormatting) {
                    Image(systemName: "textformat")
                        .frame(width: 22, height: 20)
                }
                .buttonStyle(.borderless)
                .help("Formatierung entfernen")

                Spacer()
                Text("HTML")
                    .font(.system(size: 9, weight: .medium))
                    .foregroundStyle(.tertiary)
            }
            .padding(.horizontal, 8)
            .frame(height: 30)
            .background(.background.opacity(0.45))

            Divider()

            RichTextEditorBridge(
                plainText: $plainText,
                html: $html,
                controller: controller
            )
        }
        .frame(height: 176)
        .background(.background.opacity(0.72))
        .clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: 10, style: .continuous)
                .stroke(.quaternary, lineWidth: 1)
        )
    }

    private func formatButton(title: String, help: String, action: @escaping () -> Void) -> some View {
        Button(action: action) {
            Text(title)
                .frame(width: 22, height: 20)
        }
        .buttonStyle(.borderless)
        .help(help)
    }
}

private struct RichTextEditorBridge: NSViewRepresentable {
    @Binding var plainText: String
    @Binding var html: String
    let controller: RichTextEditorController

    func makeCoordinator() -> Coordinator {
        Coordinator(parent: self)
    }

    func makeNSView(context: Context) -> NSScrollView {
        let scrollView = NSScrollView()
        scrollView.hasVerticalScroller = true
        scrollView.borderType = .noBorder
        scrollView.drawsBackground = false

        let textView = NSTextView()
        textView.isRichText = true
        textView.allowsUndo = true
        textView.drawsBackground = false
        textView.font = NSFont.systemFont(ofSize: 14)
        textView.textContainerInset = NSSize(width: 8, height: 8)
        textView.isVerticallyResizable = true
        textView.isHorizontallyResizable = false
        textView.autoresizingMask = [.width]
        textView.textContainer?.widthTracksTextView = true
        textView.delegate = context.coordinator

        scrollView.documentView = textView
        controller.textView = textView
        context.coordinator.loadExternalValue(into: textView, force: true)
        return scrollView
    }

    func updateNSView(_ scrollView: NSScrollView, context: Context) {
        context.coordinator.parent = self
        guard let textView = scrollView.documentView as? NSTextView else { return }
        controller.textView = textView
        context.coordinator.loadExternalValue(into: textView, force: false)
    }

    final class Coordinator: NSObject, NSTextViewDelegate {
        var parent: RichTextEditorBridge
        private var isApplyingExternalValue = false

        init(parent: RichTextEditorBridge) {
            self.parent = parent
        }

        func loadExternalValue(into textView: NSTextView, force: Bool) {
            guard force || textView.string != parent.plainText else { return }
            isApplyingExternalValue = true
            defer { isApplyingExternalValue = false }

            if !parent.html.isEmpty,
               let data = parent.html.data(using: .utf8),
               let attributed = try? NSAttributedString(
                    data: data,
                    options: [
                        .documentType: NSAttributedString.DocumentType.html,
                        .characterEncoding: String.Encoding.utf8.rawValue
                    ],
                    documentAttributes: nil
               ) {
                textView.textStorage?.setAttributedString(attributed)
            } else {
                textView.textStorage?.setAttributedString(
                    NSAttributedString(
                        string: parent.plainText,
                        attributes: [.font: NSFont.systemFont(ofSize: 14)]
                    )
                )
            }
        }

        func textDidChange(_ notification: Notification) {
            guard !isApplyingExternalValue,
                  let textView = notification.object as? NSTextView else { return }
            parent.plainText = textView.string
            parent.html = Self.html(from: textView.attributedString())
        }

        private static func html(from attributed: NSAttributedString) -> String {
            guard attributed.length > 0 else { return "" }
            do {
                let data = try attributed.data(
                    from: NSRange(location: 0, length: attributed.length),
                    documentAttributes: [
                        .documentType: NSAttributedString.DocumentType.html,
                        .characterEncoding: String.Encoding.utf8.rawValue
                    ]
                )
                return String(data: data, encoding: .utf8) ?? ""
            } catch {
                return ""
            }
        }
    }
}
'''
(root / "app" / "RichTextMailEditor.swift").write_text(rich_editor)

# -----------------------------------------------------------------------------
# Overlay: replace both preview TextEditors with the same compact rich HTML
# editor. Keep only the subject field for new mail.
# -----------------------------------------------------------------------------
p = root / "app" / "OverlayView.swift"
s = p.read_text()
old_preview = '''            if state.outputMode == .newMail {\n                VStack(alignment: .leading, spacing: 6) {\n                    Text("Betreff").font(.caption).foregroundStyle(.secondary)\n                    TextField("Betreff", text: $state.newMailSubject)\n                        .textFieldStyle(.roundedBorder)\n                }\n\n                VStack(alignment: .leading, spacing: 6) {\n                    Text("Mailtext").font(.caption).foregroundStyle(.secondary)\n                    TextEditor(text: $state.reply)\n                        .font(.body)\n                        .frame(height: 190)\n                        .padding(8)\n                        .background(.background.opacity(0.7), in: RoundedRectangle(cornerRadius: 12))\n                }\n            } else {\n                TextEditor(text: $state.reply)\n                    .font(.body)\n                    .frame(height: 190)\n                    .padding(8)\n                    .background(.background.opacity(0.7), in: RoundedRectangle(cornerRadius: 12))\n            }\n'''
new_preview = '''            if state.outputMode == .newMail {\n                TextField("Betreff", text: $state.newMailSubject)\n                    .textFieldStyle(.roundedBorder)\n            }\n\n            RichTextMailEditor(\n                plainText: $state.reply,\n                html: $state.replyHTML\n            )\n'''
s = must_replace(s, old_preview, new_preview, "Overlay rich preview")
p.write_text(s)

# -----------------------------------------------------------------------------
# AppDelegate: reset stale HTML for newly generated AI text and paste HTML/RTF
# into Outlook so what the user sees in Replyzen is what Outlook receives.
# -----------------------------------------------------------------------------
p = root / "app" / "AppDelegate.swift"
s = p.read_text()
s = must_replace(
    s,
    '''                case .success(let text):\n                    self.state.reply = text\n                    self.state.stage = .preview\n''',
    '''                case .success(let text):\n                    self.state.replyHTML = ""\n                    self.state.reply = text\n                    self.state.stage = .preview\n''',
    "reset reply HTML",
)
s = must_replace(
    s,
    '''                case .success(let draft):\n                    self.state.newMailSubject = draft.subject.trimmingCharacters(in: .whitespacesAndNewlines)\n                    self.state.reply = draft.body.trimmingCharacters(in: .whitespacesAndNewlines)\n                    self.state.stage = .preview\n''',
    '''                case .success(let draft):\n                    self.state.newMailSubject = draft.subject.trimmingCharacters(in: .whitespacesAndNewlines)\n                    self.state.replyHTML = ""\n                    self.state.reply = draft.body.trimmingCharacters(in: .whitespacesAndNewlines)\n                    self.state.stage = .preview\n''',
    "reset new-mail HTML",
)

s = s.replace("copyToPasteboard(reply)\n            showError(\"Replyzen braucht Bedienungshilfen", "copyMailToPasteboard(plainText: reply, html: state.replyHTML)\n            showError(\"Replyzen braucht Bedienungshilfen", 1)
s = s.replace("        copyToPasteboard(reply)\n        panel.hide()", "        copyMailToPasteboard(plainText: reply, html: state.replyHTML)\n        panel.hide()", 1)

old_newmail_start = '''        let subject = state.newMailSubject.trimmingCharacters(in: .whitespacesAndNewlines)\n        let body = state.reply.trimmingCharacters(in: .whitespacesAndNewlines)\n        guard !body.isEmpty else { return }\n\n        guard let pid = outlook.runningPID() else {\n            copyToPasteboard(body)\n'''
new_newmail_start = '''        let subject = state.newMailSubject.trimmingCharacters(in: .whitespacesAndNewlines)\n        let body = state.reply.trimmingCharacters(in: .whitespacesAndNewlines)\n        let html = state.replyHTML\n        guard !body.isEmpty else { return }\n\n        guard let pid = outlook.runningPID() else {\n            copyMailToPasteboard(plainText: body, html: html)\n'''
s = must_replace(s, old_newmail_start, new_newmail_start, "new mail html start")
s = must_replace(
    s,
    '''        guard outlook.isTrusted() else {\n            copyToPasteboard(body)\n            outlook.requestTrustPrompt()\n''',
    '''        guard outlook.isTrusted() else {\n            copyMailToPasteboard(plainText: body, html: html)\n            outlook.requestTrustPrompt()\n''',
    "new mail untrusted rich clipboard",
)
s = must_replace(
    s,
    '''            self?.keyboard.sendCommandN()\n            self?.populateNewMailDraft(subject: subject, body: body, attempt: 0)\n''',
    '''            self?.keyboard.sendCommandN()\n            self?.populateNewMailDraft(subject: subject, body: body, html: html, attempt: 0)\n''',
    "new mail rich populate call",
)
s = must_replace(
    s,
    '''    private func populateNewMailDraft(subject: String, body: String, attempt: Int) {\n''',
    '''    private func populateNewMailDraft(subject: String, body: String, html: String, attempt: Int) {\n''',
    "new mail rich populate signature",
)
s = must_replace(
    s,
    '''            let subjectDone = subject.isEmpty || self.outlook.setComposeSubjectValue(subject)\n            if self.outlook.setComposeBodyValue(body) {\n                self.finishNewMailInsertion()\n                return\n            }\n\n            // Give Outlook a short moment to finish constructing the compose window, but do not wait for many retries.\n            if attempt < 2 {\n                self.populateNewMailDraft(subject: subject, body: body, attempt: attempt + 1)\n''',
    '''            let subjectDone = subject.isEmpty || self.outlook.setComposeSubjectValue(subject)\n            // Accessibility can set plain text directly, but rich formatting must be\n            // pasted from the HTML/RTF clipboard. Keep the direct path only when\n            // no rich HTML has been produced.\n            if html.isEmpty, self.outlook.setComposeBodyValue(body) {\n                self.finishNewMailInsertion()\n                return\n            }\n\n            // Give Outlook a short moment to finish constructing the compose window, but do not wait for many retries.\n            if attempt < 2 {\n                self.populateNewMailDraft(subject: subject, body: body, html: html, attempt: attempt + 1)\n''',
    "new mail rich retry",
)
s = s.replace("self.copyToPasteboard(body)\n                    self.keyboard.sendCommandV()", "self.copyMailToPasteboard(plainText: body, html: html)\n                    self.keyboard.sendCommandV()", 1)
s = s.replace("self.copyToPasteboard(body)\n                self.keyboard.sendCommandV()", "self.copyMailToPasteboard(plainText: body, html: html)\n                self.keyboard.sendCommandV()", 1)
s = s.replace("self.copyToPasteboard(body)\n                self.isRunningFlow = false", "self.copyMailToPasteboard(plainText: body, html: html)\n                self.isRunningFlow = false", 1)

copy_anchor = '''    private func copyToPasteboard(_ text: String) {\n        NSPasteboard.general.clearContents()\n        NSPasteboard.general.setString(text, forType: .string)\n    }\n'''
copy_new = '''    private func copyMailToPasteboard(plainText: String, html: String) {\n        let pasteboard = NSPasteboard.general\n        pasteboard.clearContents()\n        pasteboard.setString(plainText, forType: .string)\n\n        let cleanedHTML = html.trimmingCharacters(in: .whitespacesAndNewlines)\n        guard !cleanedHTML.isEmpty, let htmlData = cleanedHTML.data(using: .utf8) else { return }\n        pasteboard.setData(htmlData, forType: .html)\n\n        if let attributed = try? NSAttributedString(\n            data: htmlData,\n            options: [\n                .documentType: NSAttributedString.DocumentType.html,\n                .characterEncoding: String.Encoding.utf8.rawValue\n            ],\n            documentAttributes: nil\n        ),\n           let rtf = try? attributed.data(\n                from: NSRange(location: 0, length: attributed.length),\n                documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf]\n           ) {\n            pasteboard.setData(rtf, forType: .rtf)\n        }\n    }\n\n    private func copyToPasteboard(_ text: String) {\n        NSPasteboard.general.clearContents()\n        NSPasteboard.general.setString(text, forType: .string)\n    }\n'''
s = must_replace(s, copy_anchor, copy_new, "rich clipboard helper")
p.write_text(s)

# Version + build.
p = root / "app" / "Info.plist"
s = p.read_text()
s = must_replace(s, "<string>1.26.0</string>", "<string>1.27.0</string>", "Info version")
s = must_replace(s, "<string>27</string>", "<string>28</string>", "Info build")
p.write_text(s)

# Package + manifest notes.
p = root / "Build-CI.sh"
s = p.read_text()
s = s.replace("Replyzen-update-1.26.zip", "Replyzen-update-1.27.zip")
s = s.replace(
    '"notes": "Replyzen 1.26: Die ausgewählte Sprache ist jetzt strikt die Ausgabesprache. Eine deutsche Anweisung wird bei ausgewähltem US English automatisch als Inhalt verstanden und die fertige Mail auf US English formuliert, und umgekehrt."',
    '"notes": "Replyzen 1.27: Der Mailentwurf hat jetzt einen sehr kompakten WYSIWYG HTML Editor mit Fett, Kursiv, Aufzählungen, Nummerierung und Formatierung entfernen. Die Formatierung wird als HTML/RTF in Outlook übernommen. Der strikte Sprachfix aus 1.26 ist enthalten."'
)
p.write_text(s)
