#!/bin/bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE="${1:-$ROOT/source-current}"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
export REPLYZEN_TEST_CATALOG="$SOURCE/app/Resources/Localization.json"
python3 "$ROOT/tests/test_source_contracts.py" "$SOURCE"
swiftc -DLOCALIZATION_TESTS -parse-as-library "$SOURCE/app/LocalizationCore.swift" "$SOURCE/app/ResponseJSON.swift" "$ROOT/tests/ResponseJSONTests.swift" -o "$TMP/json-tests"
"$TMP/json-tests"
swiftc -parse-as-library "$SOURCE/app/ChatGPTTransferPayload.swift" "$SOURCE/app/MailPromptBuilder.swift" "$ROOT/tests/ChatGPTTransferPayloadTests.swift" -o "$TMP/payload-tests"
"$TMP/payload-tests"
cat "$ROOT/tests/ClientStubs.swift" "$SOURCE/app/ChatGPTTransferPayload.swift" "$SOURCE/app/MailPromptBuilder.swift" "$SOURCE/app/OpenAIClient.swift" > "$TMP/ClientChecks.swift"
printf '\n' >> "$TMP/ClientChecks.swift"
cat "$ROOT/tests/ClientDecoderChecks.swift" >> "$TMP/ClientChecks.swift"
swiftc -DLOCALIZATION_TESTS -parse-as-library "$SOURCE/app/LocalizationCore.swift" "$SOURCE/app/ResponseJSON.swift" "$TMP/ClientChecks.swift" -o "$TMP/client-tests"
"$TMP/client-tests"
swiftc -DLOCALIZATION_TESTS -parse-as-library -framework AppKit -framework CoreText "$SOURCE/app/MailFontResolver.swift" "$SOURCE/app/MailTypography.swift" "$ROOT/tests/MailTypographyTests.swift" -o "$TMP/typography-tests"
"$TMP/typography-tests"
bash -n "$SOURCE/Build-CI.sh"
