#!/usr/bin/env python3
from pathlib import Path
import plistlib
import sys
import unittest
ROOT = Path(sys.argv[1]); sys.argv = [sys.argv[0]]; APP = ROOT / "app"

class SourceContracts(unittest.TestCase):
    def read(self, name): return (APP / name).read_text(encoding="utf-8")
    def test_identity_and_version(self):
        info = plistlib.loads((APP / "Info.plist").read_bytes())
        self.assertEqual(info["CFBundleIdentifier"], "com.lstoever.replyzen")
        self.assertEqual(info["CFBundleDisplayName"], "ReplyZen")
        self.assertEqual(info["CFBundleShortVersionString"], "1.61.0")
        self.assertEqual(info["CFBundleVersion"], "62")
    def test_payment_is_removed_from_active_code(self):
        self.assertFalse((APP / "AttachmentTextExtractor.swift").exists())
        swift = "\n".join(p.read_text(encoding="utf-8") for p in APP.glob("*.swift"))
        lowered = swift.lower()
        for token in ["payment", "überweisung", "banknote", "paymentpreview", "paymentrecipient"]:
            self.assertNotIn(token, lowered)
    def test_outlook_overlay_has_six_actions(self):
        toolbar = self.read("OutlookToolbarButtonController.swift")
        self.assertIn("NSSize(width: 282, height: 34)", toolbar)
        for action in ["new", "reply", "replyAll", "forward", "cancel", "calendar"]:
            self.assertIn(action + "Action?()", toolbar)
        self.assertNotIn("paymentAction", toolbar)
    def test_fresh_hosting_tree_on_hidden_open(self):
        panel = self.read("FloatingPanelController.swift")
        self.assertIn("private func installFreshHostingRoot()", panel)
        self.assertIn("if !panel.isVisible", panel)
        self.assertIn("NSHostingController(rootView: OverlayView(state: state))", panel)
        self.assertIn("resizeForCurrentState(animated: false, centered: true)", panel)
        self.assertNotIn("defaults.set(", panel)
    def test_stable_native_wysiwyg_wrapper(self):
        editor = self.read("RichTextMailEditor.swift")
        toolbar = self.read("EditorToolbar.swift")
        package = (ROOT / "Package.swift").read_text(encoding="utf-8")
        self.assertIn("rich-editor-swiftui.git", package)
        self.assertIn('exact: "1.1.1"', package)
        self.assertIn("import RichEditorSwiftUI", editor)
        self.assertIn("NSViewRepresentable", editor)
        self.assertIn("RichTextView.scrollableTextView()", editor)
        self.assertNotIn("RichTextEditor(", editor)
        self.assertNotIn("RichEditorState", editor)
        self.assertIn("adapter.toggleBold", toolbar)
        self.assertIn("adapter.toggleItalic", toolbar)
        self.assertIn("MailTypography.normalizeFonts", editor)
        self.assertIn("scrollView.allowsMagnification = true", editor)
        self.assertIn("adapter.attachZoom(to: scroll)", editor)
        self.assertIn("adapter.zoomPercent", toolbar)
        self.assertIn("Editor-Zoom", toolbar)
    def test_existing_mail_calendar_paths(self):
        delegate = self.read("AppDelegate.swift")
        for flow in ["openNewMailWorkspace", "openReplyWorkspace", "openForwardWorkspace", "quickDecline", "createCalendarFromOverlay"]:
            self.assertIn(flow + "(", delegate)
        state = self.read("AppState.swift")
        for mode in ["case reply", "case newMail", "case forward", "case calendar"]:
            self.assertIn(mode, state)
    def test_calendar_invite_reader(self):
        outlook = self.read("OutlookAccessibility.swift")
        delegate = self.read("AppDelegate.swift")
        helper = self.read("OutlookCalendarItemContext.swift")
        self.assertIn("func readCalendarContext(from snapshot: Snapshot)", outlook)
        self.assertIn("readVisibleMeetingInvite", outlook)
        self.assertIn("collectCalendarNativeText", outlook)
        self.assertIn("OutlookCalendarItemContext.looksLikeMeetingInvite", outlook)
        self.assertIn("OUTLOOK ITEM TYPE: MEETING INVITATION", helper)
        self.assertIn('"annehmen"', helper)
        self.assertIn('"mit vorbehalt"', helper)
        self.assertIn('"aceptar"', helper)
        calendar_start = delegate.index("private func createCalendarFromOverlay()")
        calendar_end = delegate.index("private func quickDecline()", calendar_start)
        calendar_block = delegate[calendar_start:calendar_end]
        self.assertEqual(calendar_block.count("readCalendarContext(from: snapshot)"), 2)
        self.assertNotIn("readMail(from: snapshot)", calendar_block)
        decline_block = delegate[calendar_end:]
        self.assertIn("readMail(from: snapshot)", decline_block)
    def test_json_pipeline(self):
        client = self.read("OpenAIClient.swift")
        self.assertEqual(client.count("ResponseJSON.cleanedText(text)"), 3)
        self.assertNotIn("PaymentSuggestion", client)
        self.assertNotIn("uploadFile(", client)
        self.assertNotIn("fileIOQueue", client)
        self.assertIn('"store": false', client)
        self.assertIn("Outlook meeting invitation", client)
        self.assertIn("OUTLOOK ITEM CONTEXT", client)
    def test_typography_contract(self):
        typography = self.read("MailTypography.swift")
        self.assertIn("static let pointSize: CGFloat = 10.5", typography)
        self.assertIn('static let family = "Calibri Light"', typography)
        self.assertIn("MailTypography.baseFont", self.read("RichTextMailEditor.swift"))
    def test_new_mail_subject_uses_native_keyboard_commit(self):
        delegate = self.read("AppDelegate.swift")
        keyboard = self.read("KeyboardController.swift")
        self.assertIn("func sendCommandA()", keyboard)
        self.assertIn("self.keyboard.sendCommandA()", delegate)
        self.assertIn("self.keyboard.sendCommandV()", delegate)
        self.assertIn("self.keyboard.sendTab()", delegate)
        self.assertNotIn("setComposeSubjectValue(subject)", delegate)
    def test_window_position_contract(self):
        panel = self.read("FloatingPanelController.swift")
        self.assertIn("panel.isMovable = true", panel)
        self.assertIn("panel.isRestorable = false", panel)
        self.assertIn('panel.setFrameAutosaveName("")', panel)
        self.assertIn('defaults.removeObject(forKey: "Replyzen.FloatingPanel.Frame.v1")', panel)
        toolbar = self.read("OutlookToolbarButtonController.swift")
        self.assertIn("defaults.set(Double(toolbarOffset.x)", toolbar)
        self.assertIn("defaults.set(Double(toolbarOffset.y)", toolbar)
    def test_fast_mail_and_instruction_integrity(self):
        outlook = self.read("OutlookAccessibility.swift")
        delegate = self.read("AppDelegate.swift")
        panel = self.read("FloatingPanelController.swift")
        editor = self.read("RichTextMailEditor.swift")
        workspace = self.read("MailWorkspaceView.swift")
        client = self.read("OpenAIClient.swift")
        self.assertIn("fastMailText(in window:", outlook)
        self.assertIn('maxNodes: 4_500', outlook)
        self.assertIn('maxNodes: 6_000', outlook)
        self.assertIn("selectInstructionTextSoon(expectedText:", panel)
        self.assertIn("state.instruction == expectedText", panel)
        refresh = delegate[delegate.index("private func refreshMailContext()") : delegate.index("private func generateCurrentOutput()")]
        self.assertNotIn("instructionAtLoadStart", refresh)
        self.assertNotIn("userHasNotEdited", refresh)
        self.assertNotIn("selectInstructionTextSoon", refresh)
        self.assertNotIn("self.state.instruction = \"\"", refresh)
        self.assertNotIn("self.state.instructionHTML = \"\"", refresh)
        self.assertIn("flushPendingEdits", editor)
        self.assertIn("replyZenCommitRichEditors", editor)
        self.assertGreaterEqual(workspace.count("replyZenCommitRichEditors"), 2)
        prompt_builder = self.read("MailPromptBuilder.swift")
        self.assertIn("User instruction:", prompt_builder)
        self.assertIn("Email context:", prompt_builder)

    def test_editor_shortcuts_wrapping_and_exact_transfer_preview(self):
        editor = self.read("RichTextMailEditor.swift")
        state = self.read("AppState.swift")
        workspace = self.read("MailWorkspaceView.swift")
        delegate = self.read("AppDelegate.swift")
        client = self.read("OpenAIClient.swift")
        payload = self.read("ChatGPTTransferPayload.swift")
        preview = self.read("TransferPreviewWindowController.swift")
        self.assertIn("NSEvent.addLocalMonitorForEvents", editor)
        self.assertIn("flags.contains(.command) || flags.contains(.control)", editor)
        for call in ["view.selectAll(nil)", "view.copy(nil)", "view.paste(nil)", "view.cut(nil)"]:
            self.assertIn(call, editor)
        self.assertIn("scroll.hasHorizontalScroller = false", editor)
        self.assertIn("scroll.horizontalScrollElasticity = .none", editor)
        self.assertIn("widthTracksTextView = true", editor)
        self.assertIn("previewBeforeChatGPT", state)
        self.assertIn("Übergabe vor ChatGPT anzeigen", workspace)
        self.assertIn("TransferPreviewWindowController", delegate)
        prompt_builder = self.read("MailPromptBuilder.swift")
        self.assertNotIn("userHTML", payload)
        self.assertNotIn("user_html", payload)
        self.assertNotIn("apiJSON", payload)
        self.assertNotIn("instructionHTML", delegate[delegate.index("private func makeTransferPayload") : delegate.index("private func sendWithOptionalPreview")])
        self.assertIn("let userText = state.instruction", delegate)
        self.assertIn("makeTransferPayload(mailThread: state.mailText)", delegate)
        self.assertIn("makeTransferPayload(mailThread: nil)", delegate)
        self.assertGreaterEqual(client.count("MailPromptBuilder.make(payload: payload)"), 4)
        self.assertNotIn("commonMailRules", client)
        self.assertIn("You are an email writing assistant.", prompt_builder)
        self.assertIn(r"Language: \(payload.language)", prompt_builder)
        self.assertIn(r"Tone: \(payload.tone)", prompt_builder)
        self.assertIn(r"Compact: \(compact)", prompt_builder)
        self.assertIn("Email context:", prompt_builder)
        self.assertIn("User instruction:", prompt_builder)
        self.assertIn("textView.string = prompt.previewText", preview)
        self.assertIn("responseFormat: replyDraftResponseFormat", client)
        self.assertIn("responseFormat: newMailDraftResponseFormat", client)
        self.assertIn("An ChatGPT senden", preview)

    def test_overlay_restores_after_workspace_close(self):
        delegate = self.read("AppDelegate.swift")
        start = delegate.index("private func closePanel()")
        end = delegate.index("private func showError", start)
        block = delegate[start:end]
        self.assertIn("restoreOutlookOverlayAfterPanelClose()", block)
        helper = block[block.index("private func restoreOutlookOverlayAfterPanelClose()") :]
        self.assertIn("guard isOutlookRunning else", helper)
        normal = helper[helper.index("if let pid = outlook.runningPID()") :]
        self.assertLess(normal.index("outlook.activateOutlook(pid: pid)"), normal.index("DispatchQueue.main.asyncAfter(deadline: .now() + 0.08)"))
        self.assertLess(normal.index("DispatchQueue.main.asyncAfter(deadline: .now() + 0.08)"), normal.index("self?.toolbarButton.setSuppressed(false)"))

if __name__ == "__main__": unittest.main(verbosity=2)
