#!/usr/bin/env python3
"""ReplyZen 1.61: central System/User prompts for all email-writing calls."""
from pathlib import Path
import json
import plistlib
import sys

root = Path(sys.argv[1])
repo = root.parent
app = root / "app"


def replace_once(text: str, before: str, after: str, label: str) -> str:
    count = text.count(before)
    if count != 1:
        raise RuntimeError(f"{label}: expected exactly one match, found {count}")
    return text.replace(before, after, 1)


def replace_between(text: str, start: str, end: str, replacement: str, label: str) -> str:
    a = text.find(start)
    if a < 0:
        raise RuntimeError(f"{label}: start marker missing")
    b = text.find(end, a)
    if b < 0:
        raise RuntimeError(f"{label}: end marker missing")
    return text[:a] + replacement + text[b:]


info_path = app / "Info.plist"
info = plistlib.loads(info_path.read_bytes())
if info.get("CFBundleShortVersionString") == "1.61.0" and str(info.get("CFBundleVersion")) == "62":
    required = [
        app / "MailPromptBuilder.swift",
        app / "ChatGPTTransferPayload.swift",
        app / "OpenAIClient.swift",
    ]
    if not all(path.exists() for path in required):
        raise SystemExit("ReplyZen reports 1.61 but required prompt files are missing")
    print("ReplyZen 1.61 migration already applied")
    raise SystemExit(0)

if info.get("CFBundleShortVersionString") != "1.60.0" or str(info.get("CFBundleVersion")) != "61":
    raise SystemExit("Unexpected ReplyZen source version; refusing to modify")

# Keep the transfer payload as raw user/context data only. HTML remains local to the editor.
(app / "ChatGPTTransferPayload.swift").write_text(
'''import Foundation

/// Raw data used to build the model prompt for email writing.
/// userText is kept verbatim; mailThread is context only.
struct ChatGPTTransferPayload: Equatable {
    let mailThread: String?
    let userText: String
    let tone: String
    let language: String
    let compact: Bool
}
''',
encoding="utf-8",
)

# One central prompt builder for Reply, Reply All, New Mail, Forward and Quick Decline.
(app / "MailPromptBuilder.swift").write_text(
'''import Foundation

struct MailWritingPrompt: Equatable {
    let system: String
    let user: String

    var previewText: String {
        "SYSTEM PROMPT:\\n\\n\\(system)\\n\\nUSER PROMPT:\\n\\n\\(user)"
    }
}

enum MailPromptBuilder {
    static let systemPrompt = """
You are an email writing assistant.

Generate the requested email text strictly based on the user's instruction and the provided email context.

Rules:
- Follow the requested language.
- Follow the requested tone.
- If compact is true, keep the result short and concise.
- If compact is false, use a natural amount of detail.
- Do not invent facts, names, dates, commitments or explanations.
- Use the email thread only as context.
- Do not explain what you are doing.
- Return only the final text for the email editor.
"""

    static func make(payload: ChatGPTTransferPayload) -> MailWritingPrompt {
        let context = payload.mailThread ?? ""
        let compact = payload.compact ? "true" : "false"
        let userPrompt = """
Language: \\(payload.language)
Tone: \\(payload.tone)
Compact: \\(compact)

Email context:
\\(context)

User instruction:
\\(payload.userText)
"""
        return MailWritingPrompt(system: systemPrompt, user: userPrompt)
    }
}
''',
encoding="utf-8",
)

# AppDelegate: preserve user_text exactly, stop feeding editor HTML to the model,
# and preview the exact System/User prompt generated by the same central builder.
delegate_path = app / "AppDelegate.swift"
delegate = delegate_path.read_text(encoding="utf-8")
delegate = replace_once(
    delegate,
'''    private func makeTransferPayload(mailThread: String?) -> ChatGPTTransferPayload? {
        let userText = state.instruction.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !userText.isEmpty else { return nil }
        let html = state.instructionHTML.trimmingCharacters(in: .whitespacesAndNewlines)
        return ChatGPTTransferPayload(
            mailThread: mailThread.map { String($0.prefix(30_000)) },
            userText: userText,
            userHTML: html.isEmpty ? nil : html,
            tone: state.replyTone.rawValue,
            language: chatGPTLanguageCode(),
            compact: state.newMailCompact
        )
    }
''',
'''    private func makeTransferPayload(mailThread: String?) -> ChatGPTTransferPayload? {
        let userText = state.instruction
        guard !userText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        return ChatGPTTransferPayload(
            mailThread: mailThread.map { String($0.prefix(30_000)) },
            userText: userText,
            tone: state.replyTone.rawValue,
            language: chatGPTLanguageCode(),
            compact: state.newMailCompact
        )
    }
''',
    "verbatim user text payload",
)
delegate = replace_once(
    delegate,
'''        transferPreviewWindow.show(payload: payload) { accepted in
            if accepted { send() }
        }
''',
'''        let prompt = MailPromptBuilder.make(payload: payload)
        transferPreviewWindow.show(prompt: prompt) { accepted in
            if accepted { send() }
        }
''',
    "prompt preview wiring",
)
delegate_path.write_text(delegate, encoding="utf-8")

# Preview the exact System/User prompts instead of the old raw JSON object.
preview_path = app / "TransferPreviewWindowController.swift"
preview = preview_path.read_text(encoding="utf-8")
preview = replace_once(
    preview,
    '    func show(payload: ChatGPTTransferPayload, completion: @escaping (Bool) -> Void) {\n',
    '    func show(prompt: MailWritingPrompt, completion: @escaping (Bool) -> Void) {\n',
    "preview signature",
)
preview = replace_once(
    preview,
    '        textView.string = payload.apiJSON\n',
    '        textView.string = prompt.previewText\n',
    "preview content",
)
preview_path.write_text(preview, encoding="utf-8")

# OpenAIClient: one central prompt builder for all email-writing requests.
# The Responses API's structured output configuration remains a technical transport
# detail for existing ReplyZen body/subject/HTML decoding; it is not user input.
client_path = app / "OpenAIClient.swift"
client = client_path.read_text(encoding="utf-8")
client_section_start = '    func generateReply(\n'
client_section_end = '    private var restrainedDashInstruction: String {'
new_client_section = r'''    func generateReply(
        apiKey: String,
        payload: ChatGPTTransferPayload,
        completion: @escaping (Result<ReplyDraft, Error>) -> Void
    ) {
        let prompt = MailPromptBuilder.make(payload: payload)
        performRequest(
            apiKey: apiKey,
            instructions: prompt.system,
            input: prompt.user,
            responseFormat: replyDraftResponseFormat,
            maxOutputTokens: payload.compact ? 340 : 700,
            lowVerbosity: true
        ) { result in
            switch result {
            case .success(let text):
                do { completion(.success(try Self.decodeReplyDraft(text))) }
                catch { completion(.failure(error)) }
            case .failure(let error): completion(.failure(error))
            }
        }
    }

    func generateForwardNote(
        apiKey: String,
        payload: ChatGPTTransferPayload,
        completion: @escaping (Result<ReplyDraft, Error>) -> Void
    ) {
        let prompt = MailPromptBuilder.make(payload: payload)
        performRequest(
            apiKey: apiKey,
            instructions: prompt.system,
            input: prompt.user,
            responseFormat: replyDraftResponseFormat,
            maxOutputTokens: payload.compact ? 340 : 700,
            lowVerbosity: true
        ) { result in
            switch result {
            case .success(let text):
                do { completion(.success(try Self.decodeReplyDraft(text))) }
                catch { completion(.failure(error)) }
            case .failure(let error): completion(.failure(error))
            }
        }
    }

    func generateQuickDecline(
        apiKey: String,
        mailText: String,
        completion: @escaping (Result<String, Error>) -> Void
    ) {
        let payload = ChatGPTTransferPayload(
            mailThread: String(mailText.prefix(30_000)),
            userText: "Decline the request or invitation politely and briefly. Do not add a reason, excuse, date, promise, alternative or commitment unless it is explicitly supported by the email context.",
            tone: "friendly",
            language: "the language of the latest relevant incoming message",
            compact: true
        )
        let prompt = MailPromptBuilder.make(payload: payload)
        performRequest(
            apiKey: apiKey,
            instructions: prompt.system,
            input: prompt.user,
            model: "gpt-5.6-luna",
            reasoningEffort: "none",
            maxOutputTokens: 180,
            lowVerbosity: true,
            completion: completion
        )
    }

    struct NewMailDraft: Decodable {
        let subject: String
        let body: String
        let html: String?
    }

    func generateNewMail(
        apiKey: String,
        payload: ChatGPTTransferPayload,
        completion: @escaping (Result<NewMailDraft, Error>) -> Void
    ) {
        let prompt = MailPromptBuilder.make(payload: payload)
        performRequest(
            apiKey: apiKey,
            instructions: prompt.system,
            input: prompt.user,
            responseFormat: newMailDraftResponseFormat,
            maxOutputTokens: payload.compact ? 380 : 760,
            lowVerbosity: true
        ) { result in
            switch result {
            case .success(let text):
                do { completion(.success(try Self.decodeNewMailDraft(text))) }
                catch { completion(.failure(error)) }
            case .failure(let error): completion(.failure(error))
            }
        }
    }

    private var replyDraftResponseFormat: [String: Any] {
        [
            "type": "json_schema",
            "name": "replyzen_reply_draft",
            "strict": true,
            "schema": [
                "type": "object",
                "properties": [
                    "body": [
                        "type": "string",
                        "description": "The final email editor text only, without explanation, subject line or signature unless explicitly requested."
                    ],
                    "html": [
                        "type": "string",
                        "description": "The same final text as clean email-safe HTML using only p, br, strong, em, ul, ol and li. Use an empty string when no HTML formatting is needed."
                    ]
                ],
                "required": ["body", "html"],
                "additionalProperties": false
            ]
        ]
    }

    private var newMailDraftResponseFormat: [String: Any] {
        [
            "type": "json_schema",
            "name": "replyzen_new_mail_draft",
            "strict": true,
            "schema": [
                "type": "object",
                "properties": [
                    "subject": [
                        "type": "string",
                        "description": "A short useful subject based only on the user's instruction."
                    ],
                    "body": [
                        "type": "string",
                        "description": "The final email editor text only, without explanation or signature unless explicitly requested."
                    ],
                    "html": [
                        "type": "string",
                        "description": "The same final body as clean email-safe HTML using only p, br, strong, em, ul, ol and li. Use an empty string when no HTML formatting is needed."
                    ]
                ],
                "required": ["subject", "body", "html"],
                "additionalProperties": false
            ]
        ]
    }

'''
client = replace_between(client, client_section_start, client_section_end, new_client_section, "central mail generation section")
client = replace_once(
    client,
'''        maxOutputTokens: Int? = nil,
        lowVerbosity: Bool = false,
        completion: @escaping (Result<String, Error>) -> Void
''',
'''        maxOutputTokens: Int? = nil,
        lowVerbosity: Bool = false,
        responseFormat: [String: Any]? = nil,
        completion: @escaping (Result<String, Error>) -> Void
''',
    "response format argument",
)
client = replace_once(
    client,
'''        if lowVerbosity {
            payload["text"] = ["verbosity": "low"]
        }
''',
'''        var textConfig: [String: Any] = [:]
        if lowVerbosity {
            textConfig["verbosity"] = "low"
        }
        if let responseFormat {
            textConfig["format"] = responseFormat
        }
        if !textConfig.isEmpty {
            payload["text"] = textConfig
        }
''',
    "merge text response configuration",
)
client_path.write_text(client, encoding="utf-8")

# Prompt/data tests: no HTML input, exact user_text, explicit system/user split.
(repo / "tests" / "ChatGPTTransferPayloadTests.swift").write_text(
'''import Foundation

@main
struct ChatGPTTransferPayloadTests {
    static func main() {
        let exactInstruction = "  schreibe ein gedicht\\nmit zwei Strophen  "
        let reply = ChatGPTTransferPayload(
            mailThread: "Incoming mail thread",
            userText: exactInstruction,
            tone: "professional",
            language: "en-US",
            compact: false
        )
        let prompt = MailPromptBuilder.make(payload: reply)
        precondition(prompt.system == MailPromptBuilder.systemPrompt)
        precondition(prompt.system.contains("You are an email writing assistant."))
        precondition(prompt.system.contains("Do not invent facts, names, dates, commitments or explanations."))
        precondition(prompt.user.contains("Language: en-US"))
        precondition(prompt.user.contains("Tone: professional"))
        precondition(prompt.user.contains("Compact: false"))
        precondition(prompt.user.contains("Email context:\\nIncoming mail thread"))
        precondition(prompt.user.hasSuffix("User instruction:\\n" + exactInstruction))
        precondition(!prompt.user.lowercased().contains("user_html"))
        precondition(!prompt.user.lowercased().contains("<html"))

        let newMail = ChatGPTTransferPayload(
            mailThread: nil,
            userText: "Invite Stefan for lunch.",
            tone: "friendly",
            language: "de",
            compact: true
        )
        let newPrompt = MailPromptBuilder.make(payload: newMail)
        precondition(newPrompt.user.contains("Language: de"))
        precondition(newPrompt.user.contains("Tone: friendly"))
        precondition(newPrompt.user.contains("Compact: true"))
        precondition(newPrompt.user.contains("Email context:\\n\\nUser instruction:\\nInvite Stefan for lunch."))
        precondition(newPrompt.previewText.contains("SYSTEM PROMPT:"))
        precondition(newPrompt.previewText.contains("USER PROMPT:"))
        print("PASS: central mail prompt preserves user_text and sends only requested context/settings")
    }
}
''',
encoding="utf-8",
)

# Update the test runner so both prompt builder and client compile in isolation.
run_tests_path = repo / "tests" / "run-tests.sh"
run_tests = run_tests_path.read_text(encoding="utf-8")
run_tests = replace_once(
    run_tests,
'''swiftc -parse-as-library "$SOURCE/app/ChatGPTTransferPayload.swift" "$ROOT/tests/ChatGPTTransferPayloadTests.swift" -o "$TMP/payload-tests"
''',
'''swiftc -parse-as-library "$SOURCE/app/ChatGPTTransferPayload.swift" "$SOURCE/app/MailPromptBuilder.swift" "$ROOT/tests/ChatGPTTransferPayloadTests.swift" -o "$TMP/payload-tests"
''',
    "prompt payload test compile",
)
run_tests = replace_once(
    run_tests,
'''cat "$ROOT/tests/ClientStubs.swift" "$SOURCE/app/ChatGPTTransferPayload.swift" "$SOURCE/app/OpenAIClient.swift" > "$TMP/ClientChecks.swift"
''',
'''cat "$ROOT/tests/ClientStubs.swift" "$SOURCE/app/ChatGPTTransferPayload.swift" "$SOURCE/app/MailPromptBuilder.swift" "$SOURCE/app/OpenAIClient.swift" > "$TMP/ClientChecks.swift"
''',
    "client prompt builder compile",
)
run_tests_path.write_text(run_tests, encoding="utf-8")

# Source-level regression contracts.
contracts_path = repo / "tests" / "test_source_contracts.py"
contracts = contracts_path.read_text(encoding="utf-8")
contracts = contracts.replace('self.assertEqual(info["CFBundleShortVersionString"], "1.60.0")', 'self.assertEqual(info["CFBundleShortVersionString"], "1.61.0")')
contracts = contracts.replace('self.assertEqual(info["CFBundleVersion"], "61")', 'self.assertEqual(info["CFBundleVersion"], "62")')
contracts = replace_once(
    contracts,
'''        self.assertIn("user_text is authoritative", client)
''',
'''        prompt_builder = self.read("MailPromptBuilder.swift")
        self.assertIn("User instruction:", prompt_builder)
        self.assertIn("Email context:", prompt_builder)
''',
    "old JSON prompt contract",
)
old_preview_contract = '''        self.assertNotIn("let action:", payload)
        self.assertNotIn("\\"action\\"", payload)
        self.assertNotIn("makeTransferPayload(action:", delegate)
        self.assertIn("makeTransferPayload(mailThread: state.mailText)", delegate)
        self.assertIn("makeTransferPayload(mailThread: nil)", delegate)
        self.assertGreaterEqual(client.count("input: payload.apiJSON"), 3)
        self.assertIn("mail_thread is context only", client)
        self.assertIn("Do not invent or infer facts", client)
        self.assertIn("sortedKeys", payload)
        self.assertIn("textView.string = payload.apiJSON", preview)
        self.assertIn("An ChatGPT senden", preview)
'''
new_preview_contract = '''        prompt_builder = self.read("MailPromptBuilder.swift")
        self.assertNotIn("userHTML", payload)
        self.assertNotIn("user_html", payload)
        self.assertNotIn("apiJSON", payload)
        self.assertNotIn("instructionHTML", delegate[delegate.index("private func makeTransferPayload") : delegate.index("private func sendWithOptionalPreview")])
        self.assertIn("let userText = state.instruction", delegate)
        self.assertIn("makeTransferPayload(mailThread: state.mailText)", delegate)
        self.assertIn("makeTransferPayload(mailThread: nil)", delegate)
        self.assertGreaterEqual(client.count("MailPromptBuilder.make(payload: payload)"), 4)
        self.assertNotIn("commonMailRules", client)
        self.assertIn("You are an email writing assistant.", prompt_builder)
        self.assertIn("Language: \\(payload.language)", prompt_builder)
        self.assertIn("Tone: \\(payload.tone)", prompt_builder)
        self.assertIn("Compact: \\(compact)", prompt_builder)
        self.assertIn("Email context:", prompt_builder)
        self.assertIn("User instruction:", prompt_builder)
        self.assertIn("textView.string = prompt.previewText", preview)
        self.assertIn("responseFormat: replyDraftResponseFormat", client)
        self.assertIn("responseFormat: newMailDraftResponseFormat", client)
        self.assertIn("An ChatGPT senden", preview)
'''
contracts = replace_once(contracts, old_preview_contract, new_preview_contract, "central prompt source contract")
contracts_path.write_text(contracts, encoding="utf-8")

# Version and localized release notes.
info["CFBundleShortVersionString"] = "1.61.0"
info["CFBundleVersion"] = "62"
info_path.write_bytes(plistlib.dumps(info, fmt=plistlib.FMT_XML, sort_keys=False))

notes_de = (
    "ReplyZen 1.61: Die ChatGPT-Übergabe für Reply, Reply All, New Mail, Forward und die Schnell-Absage nutzt jetzt zentral einen klaren System- und User-Prompt. "
    "Der User-Prompt enthält nur Sprache, Ton, Compact, den relevanten Mailverlauf als Kontext und den unveränderten geschriebenen Nutzertext. user_html wird nicht mehr an das Modell gesendet. "
    "Die optionale Vorschau zeigt jetzt genau den System- und User-Prompt vor dem Senden. Bestehende Mail-, Betreff-, Outlook- und Editorabläufe bleiben unverändert."
)
notes = {
    "de": notes_de,
    "en-US": (
        "ReplyZen 1.61: ChatGPT handoff for Reply, Reply All, New Mail, Forward and Quick Decline now uses one central, explicit System/User prompt. "
        "The User prompt contains only language, tone, Compact, the relevant mail thread as context, and the user's written instruction verbatim. user_html is no longer sent to the model. "
        "The optional preview now shows the exact System and User prompts before sending. Existing mail, subject, Outlook and editor flows remain unchanged."
    ),
    "es": (
        "ReplyZen 1.61: La transferencia a ChatGPT para Reply, Reply All, New Mail, Forward y Quick Decline utiliza ahora un único prompt central y explícito de System/User. "
        "El prompt de usuario contiene solo idioma, tono, Compact, el hilo relevante como contexto y la instrucción escrita del usuario sin modificar. user_html ya no se envía al modelo. "
        "La vista previa opcional muestra ahora exactamente los prompts de System y User antes del envío. Los flujos existentes de correo, asunto, Outlook y editor no cambian."
    ),
}
(root / "Release-notes.txt").write_text(notes_de + "\n", encoding="utf-8")
(root / "Release-notes.localized.json").write_text(json.dumps(notes, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

verify_path = repo / "tests" / "verify_update.py"
verify = verify_path.read_text(encoding="utf-8")
verify = verify.replace("manifest['version'] == '1.60.0' and manifest['build'] == 61", "manifest['version'] == '1.61.0' and manifest['build'] == 62")
verify = verify.replace("manifest['download_url'] == 'Replyzen-update-1.60.zip'", "manifest['download_url'] == 'Replyzen-update-1.61.zip'")
verify = verify.replace("PASS: 1.60 version/build", "PASS: 1.61 version/build")
verify_path.write_text(verify, encoding="utf-8")

print("Migrated ReplyZen to 1.61.0 / build 62")
